### ISSUE TITLE
librosa error

### ISSUE THREAD

**Issue by crankyz** [filippogiruzzi/voice_activity_detection#10]
Hello,thank you for your work, when running  python3 data_processing/data_to_tfrecords.py --data_dir /path/to/LibriSpeech/ on your provided test-clean

got this error 
librosa.util.exceptions.ParameterError: Since S.shape[0] is 128, frame_length is expected to be 254 or 255; found 512

any suggesion? tf=1.14 cant find 1.12.0 if this matter. Thank you.

**Comment by ulitaig** [comment]
I meet the same problem, and this is my solution：

Change librosa to version 0.7.0 and change numba to version 0.48.0.

**Comment by zhouzhou0322** [comment]
find  vad-->data_processing-->extract_features around line 15, change as below,

rmse = librosa.feature.rms(S=mel_spectogram, frame_length=mel_spectogram.shape[0]*2-1, hop_length=step)

hope this will solve your problems

**Comment by filippogiruzzi** [comment]
> Change librosa to version 0.7.0 and change numba to version 0.48.0.

#This should solve this kind of issue, and it has been added to the requirements.
