### ISSUE TITLE
where to find pretrained model?

### ISSUE THREAD

**Issue by bluegrey2006** [filippogiruzzi/voice_activity_detection#12]
Hi, is there a pretrain VAD model to recommend?

**Comment by filippogrz** [comment]
Hello, you can find a pre-trained model **for prediction only** in this [drive](https://drive.google.com/drive/folders/1ZPQ6wnMhHeE7XP5dqpAEmBAryFzESlin?usp=sharing).

I have not release a pre-trained model for fine-tuning yet.

**Comment by filippogiruzzi** [comment]
Hello, you can find a pre-trained model for prediction only in this drive.

I have not release a pre-trained model for fine-tuning yet.
